version: "2"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 30
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 28
  identical-code:
    enabled: true
    config:
      threshold: 28

exclude_patterns:
  - "config/"
  - "db/"
  - "**/node_modules/"
  - "script/"
  - "src/Commands/"
  - "src/Exceptions/"
  - "src/Utils/ErrorMessages.php"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
