<?php

namespace ForestAdmin\LaravelForestAdmin\Tests\Utils;

/**
 * Class FakeSchema
 *
 * @package Laravel-forestadmin
 * @license GNU https://www.gnu.org/licenses/licenses.html
 * @link    https://github.com/ForestAdmin/laravel-forestadmin
 */
trait FakeSchema
{
    /**
     * @param bool $convertToJson
     * @return array|false|string
     * @throws \JsonException
     */
    public function fakeSchema(bool $convertToJson = true)
    {
        $schema = [
            "collections" => [
                [
                    "name"    => "book",
                    "class"   => "ForestAdmin\LaravelForestAdmin\Tests\Utils\Models\Book",
                    "fields"  => [
                        [
                            "field"         => "id",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "published_at",
                            "type"          => "Date",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "sold_at",
                            "type"          => "Dateonly",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "label",
                            "type"          => "String",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "difficulty",
                            "type"          => "Enum",
                            "default_value" => null,
                            "enums"         => [
                                "easy",
                                "hard",
                            ],
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "comments",
                            "type"          => ["Number"],
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => "comment.id",
                            "inverse_of"    => "book",
                            "widget"        => null,
                            "validations"   => [],
                            "relationship"  => "HasMany",
                        ],
                        [
                            "field"         => "editor",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => "editor.id",
                            "inverse_of"    => "book",
                            "widget"        => null,
                            "validations"   => [],
                            "relationship"  => "HasOne",
                        ],
                        [
                            "field"         => "category",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => true,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => "category.id",
                            "inverse_of"    => "book",
                            "widget"        => null,
                            "validations"   => [],
                            "relationship"  => "BelongsTo",
                        ],
                        [
                            "field"         => "reference",
                            "type"          => "String",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => false,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => false,
                            "is_virtual"    => true,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "smartBookstores",
                            "type"          => ["String"],
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => false,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => false,
                            "is_virtual"    => true,
                            "is_searchable" => null,
                            "reference"     => "bookstore.id",
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                    ],
                    "actions" => [
                        [
                            "id"         => "Book.smart action single",
                            "name"       => "smart action single",
                            "methodName" => "smartActionSingle",
                            "fields"     => [],
                            "endpoint"   => "\/forest\/smart-actions\/book_smart-action-single",
                            "type"       => "single",
                            "download"   => false,
                            "hooks"      => [
                                "load"   => false,
                                "change" => [],
                            ],
                        ],
                        [
                            "id"         => "Book.smart action bulk",
                            "name"       => "smart action bulk",
                            "methodName" => "smartActionBulk",
                            "fields"     => [],
                            "endpoint"   => "\/forest\/smart-actions\/book_smart-action-bulk",
                            "type"       => "bulk",
                            "download"   => false,
                            "hooks"      => [
                                "load"   => false,
                                "change" => [],
                            ],
                        ],
                    ],
                ],
                [
                    "name"   => "editor",
                    "class"  => "ForestAdmin\LaravelForestAdmin\Tests\Utils\Models\Editor",
                    "fields" => [
                        [
                            "field"         => "id",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "name",
                            "type"          => "String",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => true,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "book_id",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => true,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                    ],
                ],
                [
                    "name"    => "movie",
                    "class"   => "ForestAdmin\LaravelForestAdmin\Tests\Utils\Models\Movie",
                    "fields"  => [
                        [
                            "field"         => "id",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "body",
                            "type"          => "String",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "book",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => "book.id",
                            "inverse_of"    => "movie",
                            "widget"        => null,
                            "validations"   => [],
                            "relationship"  => "BelongsTo",
                        ],
                        [
                            "field"         => "smartCategory",
                            "type"          => "String",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => false,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => false,
                            "is_virtual"    => true,
                            "is_searchable" => null,
                            "reference"     => "category.id",
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                    ],
                    "actions" => [],
                ],
                [
                    "name"                   => "category",
                    "class"                  => "ForestAdmin\LaravelForestAdmin\Tests\Utils\Models\Category",
                    "icon"                   => null,
                    "is_read_only"           => false,
                    "is_virtual"             => false,
                    "is_searchable"          => true,
                    "only_for_relationships" => false,
                    "pagination_type"        => "page",
                    "fields"                 => [
                        [
                            "field"         => "id",
                            "type"          => "Number",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "label",
                            "type"          => "String",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => true,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "created_at",
                            "type"          => "Date",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                        [
                            "field"         => "updated_at",
                            "type"          => "Date",
                            "default_value" => null,
                            "enums"         => null,
                            "integration"   => null,
                            "is_filterable" => true,
                            "is_read_only"  => false,
                            "is_required"   => false,
                            "is_sortable"   => true,
                            "is_virtual"    => false,
                            "is_searchable" => null,
                            "reference"     => null,
                            "inverse_of"    => null,
                            "widget"        => null,
                            "validations"   => [],
                        ],
                    ],
                    "segments"               => [
                        [
                            "id"         => "Category.bestName",
                            "name"       => "bestName",
                            "methodName" => "bestCategories",
                        ],
                    ],
                    "actions"                => [],
                ],
            ],
        ];

        if ($convertToJson) {
            return json_encode($schema, JSON_THROW_ON_ERROR);
        } else {
            return $schema;
        }
    }
}
